/// Monthly budget at category x store-country grain (dbt mart fct_sales_budget).
/// Related to Product and Store through many-to-many relationships at that coarser grain.
/// Use the [Budget Amount] measure, which blanks out below budget grain.
table Budget
	isHidden
	lineageTag: 0f631c61-72f9-4d17-b608-8e94e96f4f7a

	column 'Month Start Date'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: e442e79c-31fe-4ad6-8b23-a36d0fe4dbb5
		summarizeBy: none
		sourceColumn: month_start_date

		annotation UnderlyingDateTimeDataType = Date

	column 'Category Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cfd9dcb3-7a66-4fe5-bca0-412a6db8e903
		summarizeBy: none
		sourceColumn: category_key

	column 'Store Country Code'
		dataType: string
		isHidden
		lineageTag: 10af34ac-1bff-4ff6-bf65-fd505c388969
		summarizeBy: none
		sourceColumn: store_country_code

	column 'Budget Amount'
		dataType: decimal
		isHidden
		formatString: \$#,0.00
		lineageTag: 5d0da733-8e49-4e5c-b7fe-2b5c19571967
		summarizeBy: sum
		sourceColumn: budget_amount_usd

	partition Budget = m
		mode: import
		source =
				let
				    Source = fnLoadTable("fct_sales_budget"),
				    Selected = Table.SelectColumns(Source, {"month_start_date", "category_key", "store_country_code", "budget_amount_usd"}, MissingField.Error),
				    Typed = Table.TransformColumnTypes(Selected, {{"month_start_date", type date}, {"category_key", Int64.Type}, {"store_country_code", type text}, {"budget_amount_usd", Currency.Type}})
				in
				    Typed

	annotation PBI_ResultType = Table

