/// Calendar (dbt mart dim_date), marked as the model's date table. Covers complete years.
table Date
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Key'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: date_key

	column Year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: year

	column 'Quarter Number'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: quarter_number

	column Quarter
		dataType: string
		summarizeBy: none
		sourceColumn: quarter
		sortByColumn: 'Quarter Number'

	column 'Year Quarter'
		dataType: string
		summarizeBy: none
		sourceColumn: year_quarter
		sortByColumn: 'Year Quarter Number'

	column 'Year Quarter Number'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: year_quarter_number

	column 'Month Number'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: month_number

	column Month
		dataType: string
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: 'Month Number'

	column 'Month Short'
		dataType: string
		summarizeBy: none
		sourceColumn: month_short
		sortByColumn: 'Month Number'

	column 'Year Month'
		dataType: string
		summarizeBy: none
		sourceColumn: year_month
		sortByColumn: 'Year Month Number'

	column 'Year Month Number'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: year_month_number

	column 'Month Start Date'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: month_start_date

		annotation UnderlyingDateTimeDataType = Date

	column 'Day of Week Number'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: day_of_week_number

	column 'Day of Week'
		dataType: string
		summarizeBy: none
		sourceColumn: day_of_week
		sortByColumn: 'Day of Week Number'

	column 'Day of Week Short'
		dataType: string
		summarizeBy: none
		sourceColumn: day_of_week_short
		sortByColumn: 'Day of Week Number'

	column 'Day of Month'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: day_of_month

	column 'ISO Week'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: iso_week_number

	column 'Is Weekend'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: is_weekend

	/// TRUE up to the last order date. Used by the Time Intelligence calculation group.
	column 'Date With Sales'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: date_with_sales

	hierarchy Calendar

		level Year
			column: Year

		level Quarter
			column: 'Year Quarter'

		level Month
			column: 'Year Month'

		level Date
			column: Date

	partition Date = m
		mode: import
		source =
				let
				    Source = fnLoadTable("dim_date"),
				    Typed = Table.TransformColumnTypes(Source, {{"date", type date}, {"date_key", Int64.Type}, {"year", Int64.Type}, {"quarter_number", Int64.Type}, {"quarter", type text}, {"year_quarter", type text}, {"year_quarter_number", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"month_short", type text}, {"year_month", type text}, {"year_month_number", Int64.Type}, {"month_start_date", type date}, {"day_of_week_number", Int64.Type}, {"day_of_week", type text}, {"day_of_week_short", type text}, {"day_of_month", Int64.Type}, {"iso_week_number", Int64.Type}, {"is_weekend", type logical}, {"date_with_sales", type logical}})
				in
				    Typed

	annotation PBI_ResultType = Table

