/// Calendar (dbt mart dim_date), marked as the model's date table. Covers complete years.
table Date
	lineageTag: fb7d8835-f3c7-476b-b8f9-8485eb48da15
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 06001172-be07-40f7-a65c-d57773303147
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c3b28de4-f08b-4ccd-9304-613e5e65dd43
		summarizeBy: none
		sourceColumn: date_key

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 08a60d58-9567-4311-aa1b-728b348315c1
		summarizeBy: none
		sourceColumn: year

	column 'Quarter Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a99959e7-9d6f-41ee-bd12-ad6950ea5375
		summarizeBy: none
		sourceColumn: quarter_number

	column Quarter
		dataType: string
		lineageTag: e9ba790c-25bc-4cd2-9547-6eb7942d6f23
		summarizeBy: none
		sourceColumn: quarter
		sortByColumn: 'Quarter Number'

	column 'Year Quarter'
		dataType: string
		lineageTag: 61aaa157-0bb4-4b52-adc4-4fc5788b177a
		summarizeBy: none
		sourceColumn: year_quarter
		sortByColumn: 'Year Quarter Number'

	column 'Year Quarter Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 48a9a37d-c80d-413e-ac0b-1f0c8fc68bfb
		summarizeBy: none
		sourceColumn: year_quarter_number

	column 'Month Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee77a645-6fc9-41a0-a773-944599539018
		summarizeBy: none
		sourceColumn: month_number

	column Month
		dataType: string
		lineageTag: 0a351a2d-37f3-45aa-8500-388729b51729
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: 'Month Number'

	column 'Month Short'
		dataType: string
		lineageTag: 3e66a49c-2e36-4c6f-80d7-c7e3a16d8d50
		summarizeBy: none
		sourceColumn: month_short
		sortByColumn: 'Month Number'

	column 'Year Month'
		dataType: string
		lineageTag: 45ea027d-3a04-483d-99b1-6eb5011aa2bb
		summarizeBy: none
		sourceColumn: year_month
		sortByColumn: 'Year Month Number'

	column 'Year Month Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e645a939-8ef9-41a3-9449-c4560a8a869a
		summarizeBy: none
		sourceColumn: year_month_number

	/// First day of the month. Use it on line and area charts for a continuous monthly axis.
	column 'Month Start Date'
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: b1c6fc06-bedf-41f8-a1ca-da5c56d1c505
		summarizeBy: none
		sourceColumn: month_start_date

		annotation UnderlyingDateTimeDataType = Date

	column 'Day of Week Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 05406123-46db-461a-a4c5-7610788360fa
		summarizeBy: none
		sourceColumn: day_of_week_number

	column 'Day of Week'
		dataType: string
		lineageTag: d3c36c97-140b-4e06-814c-0b7144799485
		summarizeBy: none
		sourceColumn: day_of_week
		sortByColumn: 'Day of Week Number'

	column 'Day of Week Short'
		dataType: string
		lineageTag: 3c1a6a1b-b263-4c9c-8297-542f410adf76
		summarizeBy: none
		sourceColumn: day_of_week_short
		sortByColumn: 'Day of Week Number'

	column 'Day of Month'
		dataType: int64
		formatString: 0
		lineageTag: 2f04a01c-d987-4dd5-aa9d-b1131c77b4b3
		summarizeBy: none
		sourceColumn: day_of_month

	column 'ISO Week'
		dataType: int64
		formatString: 0
		lineageTag: dc9e5326-fa10-4c55-aa5a-2a04ff259654
		summarizeBy: none
		sourceColumn: iso_week_number

	column 'Is Weekend'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b121fcbc-44b7-4b73-84a2-ac65e21e157b
		summarizeBy: none
		sourceColumn: is_weekend

	/// TRUE up to the last order date. Used by the Time Intelligence calculation group.
	column 'Date With Sales'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 24908391-4198-4bf9-84b5-b4ddf2106cb6
		summarizeBy: none
		sourceColumn: date_with_sales

	hierarchy Calendar
		lineageTag: 43c4b872-dedc-4570-8509-bf7220d32be8

		level Year
			lineageTag: 77c9c05d-fd5c-492b-8156-a50d9af8ceb2
			column: Year

		level Quarter
			lineageTag: 4db8fbe1-07fd-4f02-9b7d-083bd6250266
			column: 'Year Quarter'

		level Month
			lineageTag: 6e69e8fb-d03e-4e24-8013-d18c820f0b3d
			column: 'Year Month'

		level Date
			lineageTag: 5c0c3d49-19dc-4161-99d4-4c76c0ec3bd6
			column: Date

	partition Date = m
		mode: import
		source =
				let
				    Source = fnLoadTable("dim_date"),
				    Typed = Table.TransformColumnTypes(Source, {{"date", type date}, {"date_key", Int64.Type}, {"year", Int64.Type}, {"quarter_number", Int64.Type}, {"quarter", type text}, {"year_quarter", type text}, {"year_quarter_number", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"month_short", type text}, {"year_month", type text}, {"year_month_number", Int64.Type}, {"month_start_date", type date}, {"day_of_week_number", Int64.Type}, {"day_of_week", type text}, {"day_of_week_short", type text}, {"day_of_month", Int64.Type}, {"iso_week_number", Int64.Type}, {"is_weekend", type logical}, {"date_with_sales", type logical}})
				in
				    Typed

	annotation PBI_ResultType = Table

